name: Run Telegram Bot

on:
  schedule:
    # Otomatis restart setiap 5 jam sekali biar gak terpotong limit 6 jam GitHub
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
          # Tambahkan library lain di sini kalau bot kamu butuh (misal: pip install pyrogram telethon dsb)

      - name: Run Bot
        run: |
          python bot.py
